//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3POO.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E3POO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: Brad Pitt Fecha de Nacimiento: 18/12/1963
        ///.
        /// </summary>
        internal static string actores {
            get {
                return ResourceManager.GetString("actores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppPelis {
            get {
                object obj = ResourceManager.GetObject("AppPelis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: Gustavo Cerati Fecha de Nacimiento: 11/08/1959
        ///.
        /// </summary>
        internal static string artistas {
            get {
                return ResourceManager.GetString("artistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: Yellow Album: Parachutes Artista: Coldplay Fecha de Lanzamiento: 2000
        ///
        ///
        ///Nombre: Puente Album: Bocanada Artista: Gustao Cerati Fecha de Lanzamiento: 1999
        ///
        ///
        ///Nombre: Profugos Album: Obras Cumbres Artista: Soda Stereo Fecha de Lanzamiento: 1986
        ///
        ///
        ///Nombre: En la Ciudad de la Furia Album: Obras Cumbres Artista: Soda Stereo Fecha de Lanzamiento: 1980
        ///
        ///
        ///Nombre: Crimen Album: fsafds Artista: Gustavo Cerati Fecha de Lanzamiento: gdfgdf
        ///.
        /// </summary>
        internal static string canciones {
            get {
                return ResourceManager.GetString("canciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_Dia_spotflix {
            get {
                object obj = ResourceManager.GetObject("Imagen de Dia spotflix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa {
            get {
                object obj = ResourceManager.GetObject("lupa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yellow - Coldplay
        ///Puente - Gustavo Cerati
        ///Profugos - Soda Stereo
        ///En la Ciudad de la Furia - Soda Stereo
        ///Crimen - Gustavo Cerati
        ///.
        /// </summary>
        internal static string NombreCancion {
            get {
                return ResourceManager.GetString("NombreCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: Guerra Mundial Z Actor Principal: Brad Pitt Fecha Lanzamiento: 2013
        ///
        ///
        ///Nombre: Elon Musk Reacciona al Falcon Actor Principal: Elon Musk Fecha Lanzamiento: 2020
        ///
        ///
        ///Nombre: Sacala de la Estufa Actor Principal: NiÃ±a Fecha Lanzamiento: 2020
        ///.
        /// </summary>
        internal static string peliculas {
            get {
                return ResourceManager.GetString("peliculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///
        ///Nombre: asdCanciones: asd
        ///.
        /// </summary>
        internal static string playlists {
            get {
                return ResourceManager.GetString("playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preview1 {
            get {
                object obj = ResourceManager.GetObject("preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: Matias Rojas Mail: mfrojas@miuandes.cl
        ///
        ///
        ///
        ///Nombre: Admin Mail: admin@spotflix.cl
        ///.
        /// </summary>
        internal static string usuarios {
            get {
                return ResourceManager.GetString("usuarios", resourceCulture);
            }
        }
    }
}
